=== doldur-xyz/scrapers/src/course-list/schema/course-list.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Course List Schema",
  "description": "Schema that describes complete course and section list of METU scraping",
  "type": "object",
  "properties": {
    "date-time": {
      "type": "string",
      "format": "date-time",
      "description": "Scrape date/ time"
    },

    "semester": {
      "enum": ["fall", "spring", "summer"],
      "description": "Semester for which the scraping is done"

    },

    "year": {
      "type": "string",
      "description": "School year for which the scraping is done (e.g. 2019-2020)"
    },

    "courses": {
      "type": "array",
      "items": {
        "$ref": "#/definitions/Course"
      }
    }

  },

  "required": ["date-time", "semester", "year", "courses"],

  "definitions": {
    "Course": {
      "type": "object",
      "properties": {
        "course-code": {
          "type": "number",
          "description": "METU Course code of the course (e.g. 5710229)"
        },
        "pretty-course-code": {
          "type": "string",
          "description": "Pretty course code of the course (e.g., CENG229)"
        },
        "course-name": {
          "type": "string",
          "description": "Name of the course (e.g. C PROGRAMMING)"
        },
        "campus": {
          "enum": ["ankara", "ncc"],
          "description": "Campus in which the course is offered (ankara or northern cyprus)"
        },
        "offering-department": {
          "type": "string",
          "description": "The pretty short name of the offering department (e.g. CENG)"
        },
        "credits": {
          "type": "number",
          "description": "METU credits of the corse"
        },
        "level": {
          "type": "array",
          "items": {
            "enum": ["undergraduate", "masters", "phd"]
          },
          "uniqueItems": true,
          "description": "The levels for which the courses is offered"
        },
        "sections": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Section"
          }
        }
      },
      "required": ["course-code", "pretty-course-code", "course-name", "campus", "offering-department","credits", "level", "sections"]
    },

    "Section": {
      "type": "object",
      "properties": {
        "number": {
          "type": "number",
          "description": "Section number which is unique within a course"
        },
        "instructors": {
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true,
          "description": "Instructor names for the course"
        },
        "meetings": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "day": {
                "type": "string"
              },
              "start-time": {
                "type": "string"
              },
              "end-time": {
                "type": "string"
              },
              "location": {
                "type": "string"
              }
            },
            "required": ["day", "start-time", "end-time"]
          },
          "uniqueItems": true,
          "description": "Meetings for the class"
        },
        "constraints": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "given-department": {
                "type": "string"
              },
              "surname-start": {
                "type": "string"
              },
              "surname-end": {
                "type": "string"
              },
              "min-gpa": {
                "type": "number"
              },
              "max-gpa": {
                "type": "number"
              },
              "min-year": {
                "type": "number"
              },
              "max-year": {
                "type": "number"
              },
              "start-grade": {
                "type": "string"
              },
              "end-grade": {
                "type": "string"
              }
            },
            "required": ["given-department", "surname-start", "surname-end", "min-gpa", "max-gpa", "min-year", "max-year", "start-grade", "end-grade"]
          }
        }
      },
      "required": ["number", "instructors", "meetings", "constraints"]
    }
  }
}

=== doldur-xyz/scrapers/src/course-list/schema/course-list.example.json
{
  "date-time": "2019-09-08T03:22:06.047Z",
  "semester": "fall",
  "year": "2019-2020",
  "courses": [
    {
      "course-code": 5710213,
      "pretty-course-code": "CENG213",
      "course-name": "DATA STRUCTURES",
      "campus": "ankara",
      "offering-department": "CENG",
      "credits": 4.00,
      "level": ["undergraduate"],
      "sections": [
        {
          "number": 1,
          "instructors": ["ÇİÇEKLİ FEHİME NİHAN", "STAFF"],
          "meetings": [
            {
              "day": "tuesday",
              "start-time": "15:40",
              "end-time": "17:30",
              "location": "BMB3"
            },
            {
              "day": "friday",
              "start-time": "10:40",
              "end-time": "11:30",
              "location": "BMB4"
            }
          ],
          "constraints": [
            {
              "given-department": "CENG",
              "surname-start": "AA",
              "surname-end": "DO",
              "min-gpa": 0.00,
              "max-gpa": 4.00,
              "min-year": 0,
              "max-year": 95,
              "start-grade": "Hic almayanlar veya Basarisizlar (FD ve alti)",
              "end-grade": "Hic almayanlar veya Basarisizlar (FD ve alti)"
            }
          ]
        },
        {
          "number": 2,
          "instructors": ["ERTEKİN BOLELLİ ŞEYDA", "STAFF"],
          "meetings": [
            {
              "day": "monday",
              "start-time": "13:40",
              "end-time": "15:30",
              "location": "BMB2"
            },
            {
              "day": "wednesday",
              "start-time": "11:40",
              "end-time": "12:30",
              "location": "BMB4"
            }
          ],
          "constraints": [
            {
              "given-department": "CENG",
              "surname-start": "DÖ",
              "surname-end": "OZ",
              "min-gpa": 0.00,
              "max-gpa": 4.00,
              "min-year": 0,
              "max-year": 95,
              "start-grade": "Hic almayanlar veya Basarisizlar (FD ve alti)",
              "end-grade": "Hic almayanlar veya Basarisizlar (FD ve alti)"
            }
          ]
        },
        {
          "number": 3,
          "instructors": ["SAHİLLİOĞLU YUSUF", "STAFF"],
          "meetings": [
            {
              "day": "tuesday",
              "start-time": "09:40",
              "end-time": "10:30"
            },
            {
              "day": "wednesday",
              "start-time": "13:40",
              "end-time": "15:30"
            }
          ],
          "constraints": [
            {
              "given-department": "CENG",
              "surname-start": "ÖA",
              "surname-end": "ZZ",
              "min-gpa": 0.00,
              "max-gpa": 4.00,
              "min-year": 0,
              "max-year": 95,
              "start-grade": "Hic almayanlar veya Basarisizlar (FD ve alti)",
              "end-grade": "Hic almayanlar veya Basarisizlar (FD ve alti)"
            }
          ]
        }
      ]
    },
    {
      "course-code": 2400577,
      "pretty-course-code": "HIST577",
      "course-name": "HISTORY OF THE LATE OTTOMAN EMPIRE, 1878-1922",
      "campus": "ankara",
      "offering-department": "HIST",
      "credits": 3.00,
      "level": ["masters", "phd"],
      "sections": [
        {
          "number": 1,
          "instructors": ["ŞEKER NESİM", "STAFF"],
          "meetings": [
            {
              "day": "friday",
              "start-time": "13:40",
              "end-time": "16:30",
              "location": "B04"
            }
          ],
          "constraints": [
          ]
        }
      ]
    }
  ]
}
